package com.barlala.forum.dao;

import com.barlala.forum.entity.Reply;
import com.barlala.forum.entity.ReplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface ReplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Reply
     *
     * @mbg.generated Sun Jun 21 16:58:02 CST 2020
     */
    long countByExample(ReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Reply
     *
     * @mbg.generated Sun Jun 21 16:58:02 CST 2020
     */
    int deleteByExample(ReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Reply
     *
     * @mbg.generated Sun Jun 21 16:58:02 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Reply
     *
     * @mbg.generated Sun Jun 21 16:58:02 CST 2020
     */
    int insert(Reply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Reply
     *
     * @mbg.generated Sun Jun 21 16:58:02 CST 2020
     */
    int insertSelective(Reply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Reply
     *
     * @mbg.generated Sun Jun 21 16:58:02 CST 2020
     */
    List<Reply> selectByExampleWithBLOBs(ReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Reply
     *
     * @mbg.generated Sun Jun 21 16:58:02 CST 2020
     */
    List<Reply> selectByExample(ReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Reply
     *
     * @mbg.generated Sun Jun 21 16:58:02 CST 2020
     */
    Reply selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Reply
     *
     * @mbg.generated Sun Jun 21 16:58:02 CST 2020
     */
    int updateByExampleSelective(@Param("record") Reply record, @Param("example") ReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Reply
     *
     * @mbg.generated Sun Jun 21 16:58:02 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") Reply record, @Param("example") ReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Reply
     *
     * @mbg.generated Sun Jun 21 16:58:02 CST 2020
     */
    int updateByExample(@Param("record") Reply record, @Param("example") ReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Reply
     *
     * @mbg.generated Sun Jun 21 16:58:02 CST 2020
     */
    int updateByPrimaryKeySelective(Reply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Reply
     *
     * @mbg.generated Sun Jun 21 16:58:02 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(Reply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Reply
     *
     * @mbg.generated Sun Jun 21 16:58:02 CST 2020
     */
    int updateByPrimaryKey(Reply record);
}