package com.barlala.forum.entity;

import java.util.Date;

public class Reply {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Reply.id
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Reply.topicId
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    private Integer topicId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Reply.userId
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Reply.createTime
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Reply.modifyTime
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Reply.serial
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    private Integer serial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Reply.author
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Reply.authorAvatar
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    private String authorAvatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Reply.content
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Reply
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    public Reply(Integer id, Integer topicId, Integer userId, Date createTime, Date modifyTime, Integer serial, String author, String authorAvatar) {
        this.id = id;
        this.topicId = topicId;
        this.userId = userId;
        this.createTime = createTime;
        this.modifyTime = modifyTime;
        this.serial = serial;
        this.author = author;
        this.authorAvatar = authorAvatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Reply
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    public Reply(Integer id, Integer topicId, Integer userId, Date createTime, Date modifyTime, Integer serial, String author, String authorAvatar, String content) {
        this.id = id;
        this.topicId = topicId;
        this.userId = userId;
        this.createTime = createTime;
        this.modifyTime = modifyTime;
        this.serial = serial;
        this.author = author;
        this.authorAvatar = authorAvatar;
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Reply
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    public Reply() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Reply.id
     *
     * @return the value of Reply.id
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Reply.id
     *
     * @param id the value for Reply.id
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Reply.topicId
     *
     * @return the value of Reply.topicId
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    public Integer getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Reply.topicId
     *
     * @param topicId the value for Reply.topicId
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    public void setTopicId(Integer topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Reply.userId
     *
     * @return the value of Reply.userId
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Reply.userId
     *
     * @param userId the value for Reply.userId
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Reply.createTime
     *
     * @return the value of Reply.createTime
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Reply.createTime
     *
     * @param createTime the value for Reply.createTime
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Reply.modifyTime
     *
     * @return the value of Reply.modifyTime
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Reply.modifyTime
     *
     * @param modifyTime the value for Reply.modifyTime
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Reply.serial
     *
     * @return the value of Reply.serial
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    public Integer getSerial() {
        return serial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Reply.serial
     *
     * @param serial the value for Reply.serial
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    public void setSerial(Integer serial) {
        this.serial = serial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Reply.author
     *
     * @return the value of Reply.author
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Reply.author
     *
     * @param author the value for Reply.author
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Reply.authorAvatar
     *
     * @return the value of Reply.authorAvatar
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    public String getAuthorAvatar() {
        return authorAvatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Reply.authorAvatar
     *
     * @param authorAvatar the value for Reply.authorAvatar
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    public void setAuthorAvatar(String authorAvatar) {
        this.authorAvatar = authorAvatar == null ? null : authorAvatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Reply.content
     *
     * @return the value of Reply.content
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Reply.content
     *
     * @param content the value for Reply.content
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}