package com.barlala.forum.entity;

public class Section {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Section.Id
     *
     * @mbg.generated Tue Jun 23 14:54:32 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Section.Name
     *
     * @mbg.generated Tue Jun 23 14:54:32 CST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Section
     *
     * @mbg.generated Tue Jun 23 14:54:32 CST 2020
     */
    public Section(Integer id, String name) {
        this.id = id;
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Section
     *
     * @mbg.generated Tue Jun 23 14:54:32 CST 2020
     */
    public Section() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Section.Id
     *
     * @return the value of Section.Id
     *
     * @mbg.generated Tue Jun 23 14:54:32 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Section.Id
     *
     * @param id the value for Section.Id
     *
     * @mbg.generated Tue Jun 23 14:54:32 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Section.Name
     *
     * @return the value of Section.Name
     *
     * @mbg.generated Tue Jun 23 14:54:32 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Section.Name
     *
     * @param name the value for Section.Name
     *
     * @mbg.generated Tue Jun 23 14:54:32 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}