package com.barlala.forum.entity;

import java.util.Date;

public class Topic {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Topic.Id
     *
     * @mbg.generated Fri Jul 03 14:05:17 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Topic.SectionId
     *
     * @mbg.generated Fri Jul 03 14:05:17 CST 2020
     */
    private Integer sectionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Topic.UserId
     *
     * @mbg.generated Fri Jul 03 14:05:17 CST 2020
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Topic.Title
     *
     * @mbg.generated Fri Jul 03 14:05:17 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Topic.CreateTime
     *
     * @mbg.generated Fri Jul 03 14:05:17 CST 2020
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Topic.ModifyTime
     *
     * @mbg.generated Fri Jul 03 14:05:17 CST 2020
     */
    private Date modifytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Topic.ReplyTime
     *
     * @mbg.generated Fri Jul 03 14:05:17 CST 2020
     */
    private Date replytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Topic.author
     *
     * @mbg.generated Fri Jul 03 14:05:17 CST 2020
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Topic.authorAvatar
     *
     * @mbg.generated Fri Jul 03 14:05:17 CST 2020
     */
    private String authoravatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Topic.Content
     *
     * @mbg.generated Fri Jul 03 14:05:17 CST 2020
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Topic
     *
     * @mbg.generated Fri Jul 03 14:05:17 CST 2020
     */
    public Topic(Integer id, Integer sectionid, Integer userid, String title, Date createtime, Date modifytime, Date replytime, String author, String authoravatar) {
        this.id = id;
        this.sectionid = sectionid;
        this.userid = userid;
        this.title = title;
        this.createtime = createtime;
        this.modifytime = modifytime;
        this.replytime = replytime;
        this.author = author;
        this.authoravatar = authoravatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Topic
     *
     * @mbg.generated Fri Jul 03 14:05:17 CST 2020
     */
    public Topic(Integer id, Integer sectionid, Integer userid, String title, Date createtime, Date modifytime, Date replytime, String author, String authoravatar, String content) {
        this.id = id;
        this.sectionid = sectionid;
        this.userid = userid;
        this.title = title;
        this.createtime = createtime;
        this.modifytime = modifytime;
        this.replytime = replytime;
        this.author = author;
        this.authoravatar = authoravatar;
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Topic
     *
     * @mbg.generated Fri Jul 03 14:05:17 CST 2020
     */
    public Topic() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Topic.Id
     *
     * @return the value of Topic.Id
     *
     * @mbg.generated Fri Jul 03 14:05:17 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Topic.Id
     *
     * @param id the value for Topic.Id
     *
     * @mbg.generated Fri Jul 03 14:05:17 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Topic.SectionId
     *
     * @return the value of Topic.SectionId
     *
     * @mbg.generated Fri Jul 03 14:05:17 CST 2020
     */
    public Integer getSectionid() {
        return sectionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Topic.SectionId
     *
     * @param sectionid the value for Topic.SectionId
     *
     * @mbg.generated Fri Jul 03 14:05:17 CST 2020
     */
    public void setSectionid(Integer sectionid) {
        this.sectionid = sectionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Topic.UserId
     *
     * @return the value of Topic.UserId
     *
     * @mbg.generated Fri Jul 03 14:05:17 CST 2020
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Topic.UserId
     *
     * @param userid the value for Topic.UserId
     *
     * @mbg.generated Fri Jul 03 14:05:17 CST 2020
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Topic.Title
     *
     * @return the value of Topic.Title
     *
     * @mbg.generated Fri Jul 03 14:05:17 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Topic.Title
     *
     * @param title the value for Topic.Title
     *
     * @mbg.generated Fri Jul 03 14:05:17 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Topic.CreateTime
     *
     * @return the value of Topic.CreateTime
     *
     * @mbg.generated Fri Jul 03 14:05:17 CST 2020
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Topic.CreateTime
     *
     * @param createtime the value for Topic.CreateTime
     *
     * @mbg.generated Fri Jul 03 14:05:17 CST 2020
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Topic.ModifyTime
     *
     * @return the value of Topic.ModifyTime
     *
     * @mbg.generated Fri Jul 03 14:05:17 CST 2020
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Topic.ModifyTime
     *
     * @param modifytime the value for Topic.ModifyTime
     *
     * @mbg.generated Fri Jul 03 14:05:17 CST 2020
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Topic.ReplyTime
     *
     * @return the value of Topic.ReplyTime
     *
     * @mbg.generated Fri Jul 03 14:05:17 CST 2020
     */
    public Date getReplytime() {
        return replytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Topic.ReplyTime
     *
     * @param replytime the value for Topic.ReplyTime
     *
     * @mbg.generated Fri Jul 03 14:05:17 CST 2020
     */
    public void setReplytime(Date replytime) {
        this.replytime = replytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Topic.author
     *
     * @return the value of Topic.author
     *
     * @mbg.generated Fri Jul 03 14:05:17 CST 2020
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Topic.author
     *
     * @param author the value for Topic.author
     *
     * @mbg.generated Fri Jul 03 14:05:17 CST 2020
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Topic.authorAvatar
     *
     * @return the value of Topic.authorAvatar
     *
     * @mbg.generated Fri Jul 03 14:05:17 CST 2020
     */
    public String getAuthoravatar() {
        return authoravatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Topic.authorAvatar
     *
     * @param authoravatar the value for Topic.authorAvatar
     *
     * @mbg.generated Fri Jul 03 14:05:17 CST 2020
     */
    public void setAuthoravatar(String authoravatar) {
        this.authoravatar = authoravatar == null ? null : authoravatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Topic.Content
     *
     * @return the value of Topic.Content
     *
     * @mbg.generated Fri Jul 03 14:05:17 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Topic.Content
     *
     * @param content the value for Topic.Content
     *
     * @mbg.generated Fri Jul 03 14:05:17 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}