package com.barlala.forum.entity;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.id
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.username
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.password
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.email
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.createTime
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.avatarUrl
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    private String avatarUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.topicNum
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    private Integer topicNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.permission
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    private String permission;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    public User(Integer id, String username, String password, String email, Date createTime, String avatarUrl, Integer topicNum, String permission) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.email = email;
        this.createTime = createTime;
        this.avatarUrl = avatarUrl;
        this.topicNum = topicNum;
        this.permission = permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    public User() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.id
     *
     * @return the value of User.id
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.id
     *
     * @param id the value for User.id
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.username
     *
     * @return the value of User.username
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.username
     *
     * @param username the value for User.username
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.password
     *
     * @return the value of User.password
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.password
     *
     * @param password the value for User.password
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.email
     *
     * @return the value of User.email
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.email
     *
     * @param email the value for User.email
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.createTime
     *
     * @return the value of User.createTime
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.createTime
     *
     * @param createTime the value for User.createTime
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.avatarUrl
     *
     * @return the value of User.avatarUrl
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.avatarUrl
     *
     * @param avatarUrl the value for User.avatarUrl
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl == null ? null : avatarUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.topicNum
     *
     * @return the value of User.topicNum
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    public Integer getTopicNum() {
        return topicNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.topicNum
     *
     * @param topicNum the value for User.topicNum
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    public void setTopicNum(Integer topicNum) {
        this.topicNum = topicNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.permission
     *
     * @return the value of User.permission
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.permission
     *
     * @param permission the value for User.permission
     *
     * @mbg.generated Tue Jul 07 21:10:04 CST 2020
     */
    public void setPermission(String permission) {
        this.permission = permission == null ? null : permission.trim();
    }
}